Updated Beta release 0.9.3 (#71)
* Code Generator optimization and enhancements including improved resource naming in generated configuration
* Support provider configuration with values that come from other resources
* Bug fixes

diff --git a/.github/workflows/cli-test-pipeline.yml b/.github/workflows/cli-test-pipeline.yml
--- a/.github/workflows/cli-test-pipeline.yml
+++ b/.github/workflows/cli-test-pipeline.yml
@@ -8,9 +8,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Set up Go
-        uses: actions/setup-go@v3
+        uses: actions/setup-go@v5
         with:
-          go-version: "1.21"
+          go-version: "1.22"
 
       - name: Check out code
         uses: actions/checkout@v4
@@ -78,10 +78,14 @@ jobs:
           fi
           exit 1
 
-      - name: Generate sample Terraform for message vpn client
+      - name: Failure to Generate sample Terraform due to invalid provider specific identifiers2
         run: |
-          SOLACEBROKER_REGISTRY_OVERRIDE=registry.terraform.io/solaceproducts/solacebroker SOLACEBROKER_USERNAME=admin SOLACEBROKER_PASSWORD=admin terraform-provider-solacebroker generate --url=http://localhost:8080 solacebroker_msg_vpn_rest_delivery_point.my-rdp default messageVpn.tf
-          cat messageVpn.tf
+          SOLACEBROKER_REGISTRY_OVERRIDE=registry.terraform.io/solaceproducts/solacebroker SOLACEBROKER_USERNAME=admin SOLACEBROKER_PASSWORD=admin terraform-provider-solacebroker generate --url=http://localhost:8080 solacebroker_msg_vpn_rest_delivery_point.my-rdp default messageVpn.tf || error_code=$?
+          if [ $error_code -eq 1 ]; then
+            echo "\nExpected failure accurate"
+            exit 0
+          fi
+          exit 1
 
       - name: Generate sample Terraform for message vpn
         run: |
@@ -91,13 +95,11 @@ jobs:
       - name: Test generated terraform on broker
         run: |
           # Create
-          sed -i '/# username       = "admin"/c\username       = "admin"' messageVpn.tf
-          sed -i '/# password       = "admin"/c\password       = "admin"' messageVpn.tf
-          terraform plan
-          terraform apply -auto-approve
+          TF_VAR_broker_url=http://localhost:8080 TF_VAR_broker_username=admin TF_VAR_broker_password=admin terraform plan
+          TF_VAR_broker_url=http://localhost:8080 TF_VAR_broker_username=admin TF_VAR_broker_password=admin terraform apply -auto-approve
           sleep 1
 
-      - name: Create custom messageVPN with 21 messageVpn queues (Paging Test)
+      - name: Create custom messageVPN with 22 messageVpn queues (Paging Test)
         run: |
           pushd ci/broker_vpn_q3
           # Create
@@ -106,11 +108,16 @@ jobs:
           sleep 1
           popd
 
-      - name: Confirm all 21 queues are present with paging (Paging Test)
+      - name: Confirm all 22 queues are present with paging (Paging Test)
         run: |
           SOLACEBROKER_REGISTRY_OVERRIDE=registry.terraform.io/solaceproducts/solacebroker SOLACEBROKER_USERNAME=admin SOLACEBROKER_PASSWORD=admin terraform-provider-solacebroker generate --url=http://localhost:8080 solacebroker_msg_vpn.qn another messageVpn.tf
           cat messageVpn.tf
-          grep -o 'solacebroker_msg_vpn_queue" ' messageVpn.tf | wc -l |  grep 21
+          grep -o 'solacebroker_msg_vpn_queue" ' messageVpn.tf | wc -l |  grep 22
+
+      - name: Test escape characters in resources
+        run: |
+          SOLACEBROKER_REGISTRY_OVERRIDE=registry.terraform.io/solaceproducts/solacebroker SOLACEBROKER_USERNAME=admin SOLACEBROKER_PASSWORD=admin terraform-provider-solacebroker generate --url=http://localhost:8080 solacebroker_msg_vpn_queue_subscription.test another/aperfectly%2F%24%2Fvalid%2F%24topic%2F%24%24/foo%2Fbarr messageVpn.tf
+          cat messageVpn.tf
 
       - name: Create custom messageVPN with large config
         run: |
@@ -125,6 +132,8 @@ jobs:
         run: |
           SOLACEBROKER_REGISTRY_OVERRIDE=registry.terraform.io/solaceproducts/solacebroker SOLACEBROKER_USERNAME=admin SOLACEBROKER_PASSWORD=admin terraform-provider-solacebroker generate --url=http://localhost:8080 solacebroker_msg_vpn.test test messageVpn.tf
           cat messageVpn.tf
+          # also confirm comment is generated when ancillary object is refereced
+          cat messageVpn.tf | grep depends_on
 
       - name: Generate some resources( only msg_vpn_queue) for custom messageVPN file
         run: |
diff --git a/.github/workflows/provider-test-pipeline.yml b/.github/workflows/provider-test-pipeline.yml
--- a/.github/workflows/provider-test-pipeline.yml
+++ b/.github/workflows/provider-test-pipeline.yml
@@ -8,9 +8,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Set up Go
-        uses: actions/setup-go@v3
+        uses: actions/setup-go@v5
         with:
-          go-version: "1.21"
+          go-version: "1.22"
 
       - name: Check out code
         uses: actions/checkout@v4
@@ -46,7 +46,6 @@ jobs:
           pushd ci/broker_vpn_q
           terraform plan
           popd
-          
 
       - name: Test provider on test broker
         run: |
@@ -69,10 +68,42 @@ jobs:
           rm terraform.tfstate*
           terraform import solacebroker_msg_vpn.newone new
           popd
-          # larger config
+
+      - name: Test larger config
+        run: |
           pushd ci/bigtest
           terraform plan
           terraform apply -auto-approve
           terraform plan
           terraform destroy -auto-approve
           popd
+
+      - name: Test unknown provider param, proving that the solace provider can tolerate unknown provider params until later when it is defined
+        run: |
+          pushd ci/provider_dependency
+          terraform init # sets up the random provider, which will be used to generate a random password (which will be used but login will fail)
+          bash -c "terraform apply -auto-approve &> results.out" || echo "Expecting terraform apply to fail"
+          cat results.out | grep "401 Unauthorized"
+          popd
+
+      # Skipping state upgrade test until using new SEMP schema
+      # - name: Test state upgrade
+      #   run: |
+      #     pushd ci/state_upgrade
+      #     bash -c "terraform plan &> results.out" || echo "Expecting terraform plan to fail"
+      #     cat results.out | grep "Found deprecated state key 'deprecated_att"
+      #     cp terraform.tfstate terraform.tfstate.bak
+      #     sed -i '/deprecated_att/d' terraform.tfstate # remove deprecated non-null attributes from state
+      #     terraform plan | grep "3 to add"
+      #     terraform apply -auto-approve | grep "Apply complete"
+      #     # TODO: GH actions fails on following commands, need to investigate
+      #     # diff terraform.tfstate terraform.tfstate.bak > diff.out
+      #     # ls -l
+      #     # cat diff.out
+      #     # grep ">           \"schema_version\": 0," diff.out | wc -l | grep 3 # verify schema has been upgraded
+      #     # grep ">             \"deprecated1\": null," diff.out # verify deprecated has been removed
+      #     # grep ">               \"deprecated2\": null," diff.out # verify deprecated has been removed
+      #     # grep "<               \"clear_percent\": 20," diff.out # verify string has been converted to number
+      #     # grep "<             \"egress_enabled\": true," diff.out # verify string has been converted to bool
+      #     # terraform destroy -auto-approve
+      #     popd
