GA release 1.0.0 (#73)

diff --git a/.github/workflows/provider-test-pipeline.yml b/.github/workflows/provider-test-pipeline.yml
--- a/.github/workflows/provider-test-pipeline.yml
+++ b/.github/workflows/provider-test-pipeline.yml
@@ -22,7 +22,7 @@ jobs:
         run: |
           mkdir -p $HOME/solace; chmod 777 $HOME/solace
           docker run -d -p 8080:8080 -p 55555:55555 --shm-size=1g --env username_admin_globalaccesslevel=admin --env username_admin_password=admin --env system_scaling_maxkafkabridgecount="10" --name=solace \
-            --env system_scaling_maxconnectioncount="1000" --mount type=bind,source=$HOME/solace,destination=/var/lib/solace,ro=false solace/solace-pubsub-standard:"10.6.1.52"
+            --env system_scaling_maxconnectioncount="1000" --mount type=bind,source=$HOME/solace,destination=/var/lib/solace,ro=false solace/solace-pubsub-standard:"10.8.1.126"
           while ! curl -s localhost:8080 | grep aurelia ; do sleep 1 ; done
 
       - name: Use local provider
@@ -69,6 +69,13 @@ jobs:
           terraform import solacebroker_msg_vpn.newone new
           popd
 
+      - name: Test broker object attributes override
+        run: |
+          pushd ci/brokertest
+          terraform apply -auto-approve
+          terraform plan | grep "No changes"
+          popd
+
       - name: Test larger config
         run: |
           pushd ci/bigtest
@@ -86,24 +93,23 @@ jobs:
           cat results.out | grep "401 Unauthorized"
           popd
 
-      # Skipping state upgrade test until using new SEMP schema
-      # - name: Test state upgrade
-      #   run: |
-      #     pushd ci/state_upgrade
-      #     bash -c "terraform plan &> results.out" || echo "Expecting terraform plan to fail"
-      #     cat results.out | grep "Found deprecated state key 'deprecated_att"
-      #     cp terraform.tfstate terraform.tfstate.bak
-      #     sed -i '/deprecated_att/d' terraform.tfstate # remove deprecated non-null attributes from state
-      #     terraform plan | grep "3 to add"
-      #     terraform apply -auto-approve | grep "Apply complete"
-      #     # TODO: GH actions fails on following commands, need to investigate
-      #     # diff terraform.tfstate terraform.tfstate.bak > diff.out
-      #     # ls -l
-      #     # cat diff.out
-      #     # grep ">           \"schema_version\": 0," diff.out | wc -l | grep 3 # verify schema has been upgraded
-      #     # grep ">             \"deprecated1\": null," diff.out # verify deprecated has been removed
-      #     # grep ">               \"deprecated2\": null," diff.out # verify deprecated has been removed
-      #     # grep "<               \"clear_percent\": 20," diff.out # verify string has been converted to number
-      #     # grep "<             \"egress_enabled\": true," diff.out # verify string has been converted to bool
-      #     # terraform destroy -auto-approve
-      #     popd
+      - name: Test state upgrade
+        run: |
+          pushd ci/state_upgrade
+          bash -c "terraform plan &> results.out" || echo "Expecting terraform plan to fail"
+          cat results.out | grep "Found deprecated state key 'deprecated_att"
+          cp terraform.tfstate terraform.tfstate.bak
+          sed -i '/deprecated_att/d' terraform.tfstate # remove deprecated non-null attributes from state
+          terraform plan | grep "3 to add"
+          terraform apply -auto-approve | grep "Apply complete"
+          # GH actions fails on following commands, need to investigate. Passes locally.
+          # diff terraform.tfstate terraform.tfstate.bak > diff.out
+          # ls -l
+          # cat diff.out
+          # grep ">           \"schema_version\": 0," diff.out | wc -l | grep 3 # verify schema has been upgraded
+          # grep ">             \"deprecated1\": null," diff.out # verify deprecated has been removed
+          # grep ">               \"deprecated2\": null," diff.out # verify deprecated has been removed
+          # grep "<               \"clear_percent\": 20," diff.out # verify string has been converted to number
+          # grep "<             \"egress_enabled\": true," diff.out # verify string has been converted to bool
+          # terraform destroy -auto-approve
+          popd
